server:
  port: 8080

db:
  host: 192.168.5.44
  port: 3306
  user: root
  password: "asfdsfedarjeiowvgfsd"
  dbname: ctf

jwt:
  secret: "dev-only-secret-change-in-production-abc123"
  admin_role: "admin"

rate_limit:
  submission:
    requests: 3
    window: 10s
